
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { UserTrip, Expense } from '../types';
import { DestinationHeader } from '../components/DestinationHeader';
import { ItineraryView } from '../components/ItineraryView';
import { VisaCard } from '../components/VisaCard';
import { ArrowLeft, Calendar, Wallet, Shield, Trash2, Bus, Train, Car, Info, PlusCircle, TrendingUp, Download, X, Utensils, BedDouble, Ticket, MoreHorizontal, IndianRupee, ArrowRightLeft } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip as RechartsTooltip, Legend } from 'recharts';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const TripDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [trip, setTrip] = useState<UserTrip | null>(null);
  const [activeTab, setActiveTab] = useState<'plan' | 'budget' | 'visa' | 'transport'>('plan');
  
  // Expense Modal State
  const [showExpenseModal, setShowExpenseModal] = useState(false);
  const [expenseForm, setExpenseForm] = useState<{
    amount: string;
    category: 'Food' | 'Transport' | 'Stay' | 'Activity' | 'Other';
    currency: string;
    note: string;
  }>({
    amount: '',
    category: 'Food',
    currency: '',
    note: ''
  });

  useEffect(() => {
    const savedTrips = localStorage.getItem('innroutes_trips');
    if (savedTrips && id) {
      const trips: UserTrip[] = JSON.parse(savedTrips);
      const foundTrip = trips.find(t => t.id === id);
      if (foundTrip) {
        setTrip(foundTrip);
        // Initialize currency with home currency if not already set
        setExpenseForm(prev => ({ 
            ...prev, 
            currency: prev.currency || foundTrip.data.economics.homeCurrency 
        }));
      } else {
        navigate('/trips');
      }
    } else {
        navigate('/trips');
    }
  }, [id, navigate]);

  const handleDelete = () => {
    if (confirm('Are you sure you want to delete this trip?')) {
        const savedTrips = localStorage.getItem('innroutes_trips');
        if (savedTrips) {
            const trips: UserTrip[] = JSON.parse(savedTrips);
            const newTrips = trips.filter(t => t.id !== id);
            localStorage.setItem('innroutes_trips', JSON.stringify(newTrips));
            navigate('/trips');
        }
    }
  };

  const handleSaveExpense = () => {
    if (!trip || !expenseForm.amount) return;

    const newExpense: Expense = {
        id: Date.now().toString(),
        category: expenseForm.category,
        amount: parseFloat(expenseForm.amount),
        currency: expenseForm.currency,
        note: expenseForm.note
    };

    // Update local state
    const updatedTrip = {
        ...trip,
        expenses: [newExpense, ...(trip.expenses || [])]
    };
    setTrip(updatedTrip);

    // Update Local Storage
    const savedTrips = localStorage.getItem('innroutes_trips');
    if (savedTrips) {
        const trips: UserTrip[] = JSON.parse(savedTrips);
        const tripIndex = trips.findIndex(t => t.id === trip.id);
        if (tripIndex > -1) {
            trips[tripIndex] = updatedTrip;
            localStorage.setItem('innroutes_trips', JSON.stringify(trips));
        }
    }

    // Reset and Close
    setExpenseForm({ 
        amount: '', 
        category: 'Food', 
        currency: trip.data.economics.homeCurrency,
        note: '' 
    });
    setShowExpenseModal(false);
  };

  // Helper to calculate total spent in Home Currency
  const calculateTotalSpent = (currentTrip: UserTrip) => {
    return Math.round(currentTrip.expenses?.reduce((acc, curr) => {
        let amountInHome = curr.amount;
        if (curr.currency === currentTrip.data.economics.localCurrency) {
            amountInHome = curr.amount * currentTrip.data.economics.inverseRate;
        }
        return acc + amountInHome;
    }, 0) || 0);
  };

  const handleDownloadPDF = () => {
    if (!trip) return;

    const doc = new jsPDF();

    // -- Header --
    doc.setFontSize(22);
    doc.setTextColor(26, 29, 31); // Dark
    doc.text(`Trip to ${trip.destination}`, 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.text(`${new Date(trip.startDate).toLocaleDateString()} - ${new Date(trip.endDate).toLocaleDateString()}`, 14, 28);
    doc.text(`Generated by INNROUTES`, 14, 34);

    let yPos = 45;

    // -- Visa Section --
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Visa Requirements", 14, yPos);
    yPos += 3;
    
    autoTable(doc, {
      startY: yPos,
      head: [['Type', 'Cost', 'Processing', 'Difficulty']],
      body: [[
        trip.data.visa.type,
        trip.data.visa.cost,
        trip.data.visa.processingTime,
        trip.data.visa.difficultyLevel
      ]],
      theme: 'grid',
      headStyles: { fillColor: [255, 205, 68], textColor: [0, 0, 0], fontStyle: 'bold' }, // Brand color
      styles: { fontSize: 10 }
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;

    // -- Budget Section --
    doc.setFontSize(14);
    doc.text("Budget Overview", 14, yPos);
    yPos += 3;

    const totalSpent = calculateTotalSpent(trip);
    const remaining = trip.budget - totalSpent;

    autoTable(doc, {
      startY: yPos,
      head: [['Total Budget', 'Total Spent', 'Remaining']],
      body: [[
        `${trip.budget} ${trip.data.economics.homeCurrency}`,
        `${totalSpent} ${trip.data.economics.homeCurrency}`,
        `${remaining} ${trip.data.economics.homeCurrency}`
      ]],
      theme: 'grid',
      headStyles: { fillColor: [241, 245, 249], textColor: [0, 0, 0] }, // Slate-100
      styles: { fontSize: 10 }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 15;

    // -- Itinerary Section --
    doc.setFontSize(14);
    doc.text("Detailed Itinerary", 14, yPos);
    yPos += 3;

    const itineraryRows: any[] = [];
    trip.data.itinerary.forEach(day => {
        day.activities.forEach(act => {
            itineraryRows.push([
                `Day ${day.day}`,
                act.time,
                act.title,
                act.type.charAt(0).toUpperCase() + act.type.slice(1)
            ]);
        });
    });

    autoTable(doc, {
      startY: yPos,
      head: [['Day', 'Time', 'Activity', 'Type']],
      body: itineraryRows,
      theme: 'striped',
      headStyles: { fillColor: [26, 29, 31], textColor: [255, 255, 255] }, // Dark
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 20 },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 25 }
      },
      styles: { fontSize: 9 }
    });

    doc.save(`${trip.destination.replace(/\s+/g, '_')}_Summary.pdf`);
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const getTransportIcon = (type: string) => {
    const t = type.toLowerCase();
    if (t.includes('train') || t.includes('metro') || t.includes('subway') || t.includes('rail')) return <Train size={24} />;
    if (t.includes('bus') || t.includes('shuttle')) return <Bus size={24} />;
    return <Car size={24} />;
  };

  if (!trip) return null;

  // Budget Calculations
  const totalBudget = trip.budget;
  const totalSpent = calculateTotalSpent(trip);
  const remainingBudget = totalBudget - totalSpent;
  const isOverBudget = remainingBudget < 0;

  // Chart Data Preparation (Normalized to Home Currency)
  const chartData = trip.expenses?.reduce((acc: any[], curr) => {
    const existing = acc.find(item => item.name === curr.category);
    let amountInHome = curr.amount;
    
    // Normalize to Home Currency for chart
    if (curr.currency === trip.data.economics.localCurrency) {
        amountInHome = curr.amount * trip.data.economics.inverseRate;
    }

    if (existing) {
      existing.value += amountInHome;
    } else {
      acc.push({ name: curr.category, value: amountInHome });
    }
    return acc;
  }, []) || [];

  const COLORS = ['#1a1d1f', '#ffcd44', '#94a3b8', '#e2e8f0', '#f87171'];

  const categories = [
    { id: 'Food', icon: <Utensils size={18} />, color: 'bg-orange-100 text-orange-600' },
    { id: 'Transport', icon: <Bus size={18} />, color: 'bg-blue-100 text-blue-600' },
    { id: 'Stay', icon: <BedDouble size={18} />, color: 'bg-indigo-100 text-indigo-600' },
    { id: 'Activity', icon: <Ticket size={18} />, color: 'bg-emerald-100 text-emerald-600' },
    { id: 'Other', icon: <MoreHorizontal size={18} />, color: 'bg-slate-100 text-slate-600' },
  ];

  return (
    <div className="pb-20 bg-white min-h-screen">
      {/* Custom Header with Buttons */}
      <div className="relative">
        <button 
            onClick={() => navigate('/trips')} 
            className="absolute top-4 left-4 z-10 bg-black/20 backdrop-blur-md p-2 rounded-full text-white hover:bg-black/30 transition-colors"
        >
            <ArrowLeft size={24} />
        </button>
        
        {/* Action Buttons */}
        <div className="absolute top-4 right-4 z-10 flex gap-2">
            <button 
                onClick={handleDownloadPDF} 
                className="bg-black/20 backdrop-blur-md p-2 rounded-full text-white hover:bg-black/30 transition-colors"
                title="Download Summary PDF"
            >
                <Download size={20} />
            </button>
            <button 
                onClick={handleDelete} 
                className="bg-red-500/20 backdrop-blur-md p-2 rounded-full text-red-100 hover:bg-red-500/40 transition-colors"
                title="Delete Trip"
            >
                <Trash2 size={20} />
            </button>
        </div>

        <DestinationHeader data={trip.data} />
      </div>

      {/* Trip Specific Info Bar */}
      <div className="mx-5 -mt-6 relative z-20 bg-white rounded-xl shadow-lg border border-slate-100 p-4 flex justify-between items-center">
        <div>
            <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider mb-1">Travel Dates</p>
            <div className="flex items-center gap-2 text-dark font-bold text-sm">
                <Calendar size={16} className="text-brand" />
                {formatDate(trip.startDate)} - {formatDate(trip.endDate)}
            </div>
        </div>
        <div className="text-right">
             <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider mb-1">Budget</p>
             <div className="flex items-center justify-end gap-1 text-emerald-600 font-bold text-sm">
                <Wallet size={16} />
                {trip.budget} {trip.data.economics.homeCurrency}
            </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="sticky top-0 bg-white z-30 mt-6 px-5 border-b border-slate-100 overflow-x-auto no-scrollbar pt-2">
        <div className="flex gap-6 min-w-max">
          <button
            onClick={() => setActiveTab('plan')}
            className={`pb-3 text-sm font-bold transition-colors relative ${
              activeTab === 'plan' ? 'text-black' : 'text-slate-400'
            }`}
          >
            Itinerary
            {activeTab === 'plan' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-brand rounded-full" />}
          </button>
          <button
            onClick={() => setActiveTab('visa')}
            className={`pb-3 text-sm font-bold transition-colors relative ${
              activeTab === 'visa' ? 'text-black' : 'text-slate-400'
            }`}
          >
            Visa Info
            {activeTab === 'visa' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-brand rounded-full" />}
          </button>
          <button
            onClick={() => setActiveTab('transport')}
            className={`pb-3 text-sm font-bold transition-colors relative ${
              activeTab === 'transport' ? 'text-black' : 'text-slate-400'
            }`}
          >
            Transport
            {activeTab === 'transport' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-brand rounded-full" />}
          </button>
          <button
            onClick={() => setActiveTab('budget')}
            className={`pb-3 text-sm font-bold transition-colors relative ${
              activeTab === 'budget' ? 'text-black' : 'text-slate-400'
            }`}
          >
            Expenses
            {activeTab === 'budget' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-brand rounded-full" />}
          </button>
        </div>
      </div>

      <div className="p-5">
        {activeTab === 'plan' && (
            <div className="animate-fadeIn">
                <ItineraryView days={trip.data.itinerary} />
            </div>
        )}

        {activeTab === 'visa' && (
            <div className="animate-fadeIn space-y-4">
                <VisaCard visa={trip.data.visa} />
                <div className="bg-slate-50 p-4 rounded-xl text-xs text-slate-500 leading-relaxed">
                    <div className="font-bold text-slate-700 mb-2 flex items-center gap-2">
                        <Shield size={14} />
                        Embassy Note
                    </div>
                    Always verify visa requirements with the nearest embassy before traveling. Rules can change without notice.
                </div>
            </div>
        )}

        {activeTab === 'transport' && (
          <div className="animate-fadeIn space-y-4">
             <div className="bg-blue-50 p-4 rounded-xl flex gap-3 mb-4">
                <Info size={20} className="text-blue-600 shrink-0 mt-0.5" />
                <div>
                   <h4 className="font-bold text-blue-900 text-sm">Getting Around</h4>
                   <p className="text-xs text-blue-800/80 mt-1">
                     Local transport options and estimated costs for {trip.destination}.
                   </p>
                </div>
             </div>

             {trip.data.localTransport && trip.data.localTransport.length > 0 ? (
                 trip.data.localTransport.map((option, idx) => (
                    <div key={idx} className="bg-white rounded-xl border border-slate-200 shadow-sm p-5 flex gap-4">
                       <div className="w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center text-slate-600 shrink-0">
                          {getTransportIcon(option.type)}
                       </div>
                       <div className="flex-1">
                          <div className="flex justify-between items-start mb-1">
                             <h4 className="font-bold text-slate-800">{option.type}</h4>
                             <span className="text-xs font-bold bg-green-100 text-green-700 px-2 py-1 rounded-full whitespace-nowrap">
                                {option.costLocal} {trip.data.economics.localCurrency}
                             </span>
                          </div>
                          <p className="text-sm text-slate-500 leading-relaxed">{option.routeInfo}</p>
                       </div>
                    </div>
                 ))
             ) : (
                <div className="text-center py-10 bg-slate-50 rounded-xl">
                   <p className="text-slate-400 text-sm">No transport information available for this trip.</p>
                </div>
             )}
          </div>
        )}

        {activeTab === 'budget' && (
            <div className="animate-fadeIn space-y-6">
                {/* Stats Grid */}
                <div className="grid grid-cols-3 gap-3">
                    <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
                        <p className="text-[10px] uppercase font-bold text-slate-400 mb-1">Total</p>
                        <p className="text-sm font-bold text-dark">{totalBudget} {trip.data.economics.homeCurrency}</p>
                    </div>
                    <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
                        <p className="text-[10px] uppercase font-bold text-slate-400 mb-1">Spent</p>
                        <p className="text-sm font-bold text-blue-600">{totalSpent} {trip.data.economics.homeCurrency}</p>
                    </div>
                    <div className={`p-3 rounded-xl border ${isOverBudget ? 'bg-red-50 border-red-100' : 'bg-emerald-50 border-emerald-100'}`}>
                        <p className={`text-[10px] uppercase font-bold mb-1 ${isOverBudget ? 'text-red-400' : 'text-emerald-400'}`}>Left</p>
                        <p className={`text-sm font-bold ${isOverBudget ? 'text-red-600' : 'text-emerald-600'}`}>{remainingBudget} {trip.data.economics.homeCurrency}</p>
                    </div>
                </div>

                {/* Chart Section */}
                <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
                    <h4 className="font-bold text-dark mb-4 text-sm flex items-center gap-2">
                        <TrendingUp size={16} /> Spending Breakdown
                    </h4>
                    
                    {chartData.length > 0 ? (
                        <div className="h-48 w-full">
                             <ResponsiveContainer width="100%" height="100%">
                                <PieChart>
                                <Pie
                                    data={chartData}
                                    cx="50%"
                                    cy="50%"
                                    innerRadius={40}
                                    outerRadius={60}
                                    paddingAngle={5}
                                    dataKey="value"
                                >
                                    {chartData.map((entry, index) => (
                                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                    ))}
                                </Pie>
                                <RechartsTooltip formatter={(value: number) => `${Math.round(value)} ${trip.data.economics.homeCurrency}`} />
                                <Legend verticalAlign="bottom" height={36} iconSize={8} wrapperStyle={{ fontSize: '10px' }} />
                                </PieChart>
                            </ResponsiveContainer>
                        </div>
                    ) : (
                         <div className="h-48 w-full flex flex-col items-center justify-center bg-slate-50 rounded-xl border border-dashed border-slate-200">
                             <div className="w-10 h-10 bg-slate-200 rounded-full flex items-center justify-center text-slate-400 mb-2">
                                 <Wallet size={18} />
                             </div>
                             <p className="text-xs text-slate-400 font-medium">No expenses yet</p>
                         </div>
                    )}
                </div>

                {/* Expense History List */}
                <div className="space-y-3">
                    <h4 className="font-bold text-dark text-sm">Recent Expenses</h4>
                    {trip.expenses?.length > 0 ? (
                        trip.expenses.map((exp) => (
                            <div key={exp.id} className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border border-slate-100">
                                <div className="flex items-center gap-3">
                                    <div className={`w-8 h-8 rounded-full flex items-center justify-center ${categories.find(c => c.id === exp.category)?.color}`}>
                                        {categories.find(c => c.id === exp.category)?.icon}
                                    </div>
                                    <div>
                                        <p className="text-sm font-bold text-slate-800">{exp.category}</p>
                                        {exp.note && <p className="text-xs text-slate-400">{exp.note}</p>}
                                    </div>
                                </div>
                                <span className="text-sm font-bold text-slate-700">
                                    {exp.amount} {exp.currency}
                                </span>
                            </div>
                        ))
                    ) : (
                        <p className="text-xs text-slate-400 italic">No transactions recorded.</p>
                    )}
                </div>
                
                {/* Add Button */}
                <button 
                    onClick={() => setShowExpenseModal(true)}
                    className="w-full bg-black text-brand font-bold py-4 rounded-xl shadow-lg flex items-center justify-center gap-2 hover:bg-slate-800 transition-colors"
                >
                    <PlusCircle size={20} />
                    Add Expense
                </button>
            </div>
        )}
      </div>

      {/* Add Expense Modal */}
      {showExpenseModal && (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in">
            <div className="bg-white w-full max-w-md rounded-3xl p-6 relative overflow-hidden animate-in slide-in-from-bottom-10">
                <button 
                    onClick={() => setShowExpenseModal(false)}
                    className="absolute top-4 right-4 bg-slate-100 p-2 rounded-full text-slate-500 hover:bg-slate-200"
                >
                    <X size={20} />
                </button>

                <h3 className="text-xl font-bold text-dark mb-6">Add New Expense</h3>

                <div className="space-y-6">
                    {/* Amount Input */}
                    <div className="space-y-2">
                        <div className="flex justify-between items-center">
                            <label className="text-xs font-bold text-slate-500 uppercase">Amount</label>
                            {/* Currency Toggle */}
                            <div className="flex bg-slate-100 p-0.5 rounded-lg">
                                <button
                                    onClick={() => setExpenseForm({...expenseForm, currency: trip.data.economics.homeCurrency})}
                                    className={`px-2 py-1 text-[10px] font-bold rounded-md transition-all ${expenseForm.currency === trip.data.economics.homeCurrency ? 'bg-white shadow text-black' : 'text-slate-400'}`}
                                >
                                    {trip.data.economics.homeCurrency}
                                </button>
                                <button
                                    onClick={() => setExpenseForm({...expenseForm, currency: trip.data.economics.localCurrency})}
                                    className={`px-2 py-1 text-[10px] font-bold rounded-md transition-all ${expenseForm.currency === trip.data.economics.localCurrency ? 'bg-white shadow text-black' : 'text-slate-400'}`}
                                >
                                    {trip.data.economics.localCurrency}
                                </button>
                            </div>
                        </div>
                        <div className="relative">
                            <div className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">
                                {expenseForm.currency === 'INR' ? <IndianRupee size={20} /> : <span className="font-bold text-lg text-slate-400">$</span>}
                            </div>
                            <input 
                                type="number" 
                                value={expenseForm.amount}
                                onChange={(e) => setExpenseForm({...expenseForm, amount: e.target.value})}
                                placeholder="0.00"
                                autoFocus
                                className="w-full bg-slate-50 border border-slate-200 rounded-xl pl-12 pr-16 py-4 text-2xl font-bold text-slate-800 outline-none focus:ring-2 focus:ring-brand"
                            />
                            <span className="absolute right-4 top-1/2 -translate-y-1/2 text-sm font-bold text-slate-400">
                                {expenseForm.currency}
                            </span>
                        </div>
                    </div>

                    {/* Category Selection */}
                    <div className="space-y-2">
                         <label className="text-xs font-bold text-slate-500 uppercase">Category</label>
                         <div className="grid grid-cols-5 gap-2">
                            {categories.map((cat) => (
                                <button
                                    key={cat.id}
                                    onClick={() => setExpenseForm({...expenseForm, category: cat.id as any})}
                                    className={`flex flex-col items-center justify-center gap-1 p-2 rounded-xl border transition-all ${expenseForm.category === cat.id ? 'bg-black text-brand border-black shadow-md scale-105' : 'bg-white text-slate-400 border-slate-100 hover:border-slate-300'}`}
                                >
                                    {cat.icon}
                                    <span className="text-[9px] font-bold">{cat.id}</span>
                                </button>
                            ))}
                         </div>
                    </div>

                    {/* Notes Input */}
                    <div className="space-y-2">
                        <label className="text-xs font-bold text-slate-500 uppercase">Note (Optional)</label>
                        <textarea 
                            value={expenseForm.note}
                            onChange={(e) => setExpenseForm({...expenseForm, note: e.target.value})}
                            placeholder="Dinner at night market..."
                            className="w-full bg-slate-50 border border-slate-200 rounded-xl p-4 text-sm font-medium text-slate-800 outline-none focus:ring-2 focus:ring-brand resize-none h-24"
                        />
                    </div>

                    <button 
                        onClick={handleSaveExpense}
                        disabled={!expenseForm.amount}
                        className="w-full bg-brand text-black font-bold py-4 rounded-xl shadow-lg disabled:opacity-50 disabled:cursor-not-allowed hover:bg-[#eebb33] transition-colors"
                    >
                        Save Expense
                    </button>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};
